### ISSUE TITLE
Compare Kibana server performances with APM fully disabled versus APM in `contextPropagationOnly` mode

### ISSUE THREAD

**Issue by pgayvallet** [elastic/kibana-load-testing#245]
Branch: `main`

#### Scenario 1: APM in `contextPropagationOnly` mode:

Use vanilla configuration from the branch

#### Scenario 2: APM fully disabled

Use this kibana config:

```yaml
elastic.apm:
  active: false
  contextPropagationOnly: false
```

Please tell me if you need more information
